/**
 * chatbot-client.js
 *
 * Long-lived Node <-> Python bridge for the chatbot engine.
 *
 * Why this exists: the numbers engine and the trained model are Python/PyTorch,
 * while the dashboard API is Express/Node. Rather than reimplementing the
 * analytics in JS (two sources of truth) or spawning Python per request
 * (~1s startup), we keep one warm Python process and speak line-delimited JSON.
 *
 * Numbers are never generated by the model -- they are computed in Python from
 * the CSV and returned as text. See engine.py.
 */

const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

const CHATBOT_DIR = path.join(__dirname, 'chatbot');

function findPython() {
  if (process.env.CHATBOT_PYTHON) {
    return process.env.CHATBOT_PYTHON;
  }

  return process.platform === 'win32' ? 'python' : 'python3';
}

class ChatbotClient {
  constructor() {
    this.proc = null;
    this.ready = false;
    this.pending = new Map();
    this.seq = 0;
    this.available = false;
    this.lastError = null;
    this.buffer = '';
  }

  start() {
    const script = path.join(CHATBOT_DIR, 'bridge.py');
    if (!fs.existsSync(script)) {
      this.lastError = 'bridge.py not found';
      console.warn('[chatbot] %s', this.lastError);
      return;
    }

    const exe = findPython();
    this.proc = spawn(exe, [script], {
      cwd: CHATBOT_DIR,
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true,
    });

    this.proc.stdout.on('data', (chunk) => this._onData(chunk));
    this.proc.stderr.on('data', (chunk) => {
      const s = chunk.toString().trim();
      if (s) console.log('[chatbot:py] %s', s);
    });

    this.proc.on('error', (err) => {
      this.available = false;
      this.lastError = err.message;
      console.warn('[chatbot] failed to start python: %s', err.message);
    });

    this.proc.on('exit', (code) => {
      this.available = false;
      this.ready = false;
      this.lastError = `python bridge exited (${code})`;
      console.warn('[chatbot] %s', this.lastError);
      // Fail in-flight requests fast instead of hanging the HTTP handler.
      for (const [, entry] of this.pending) {
        entry.reject(new Error(this.lastError));
      }
      this.pending.clear();
    });

    // First call doubles as the readiness probe.
    this._send('ping', {}, 15000)
      .then(() => {
        this.ready = true;
        this.available = true;
        console.log('[chatbot] engine ready');
      })
      .catch((err) => {
        this.available = false;
        this.lastError = err.message;
        console.warn('[chatbot] not available: %s', err.message);
      });
  }

  _onData(chunk) {
    this.buffer += chunk.toString();
    let idx;
    while ((idx = this.buffer.indexOf('\n')) !== -1) {
      const line = this.buffer.slice(0, idx).trim();
      this.buffer = this.buffer.slice(idx + 1);
      if (!line) continue;
      let msg;
      try {
        msg = JSON.parse(line);
      } catch (e) {
        console.warn('[chatbot] bad JSON from bridge: %s', line.slice(0, 200));
        continue;
      }
      const entry = this.pending.get(msg.id);
      if (!entry) continue;
      this.pending.delete(msg.id);
      clearTimeout(entry.timer);
      if (msg.ok) entry.resolve(msg);
      else entry.reject(new Error(msg.error || 'chatbot error'));
    }
  }

  _send(op, payload = {}, timeoutMs = 20000) {
    if (!this.proc || !this.proc.stdin.writable) {
      return Promise.reject(new Error('chatbot bridge not running'));
    }
    const id = String(++this.seq);
    const body = JSON.stringify({ id, op, ...payload });
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`chatbot timeout after ${timeoutMs}ms`));
      }, timeoutMs);
      this.pending.set(id, { resolve, reject, timer });
      this.proc.stdin.write(body + '\n');
    });
  }

  answer(question) {
    return this._send('answer', { question }, 20000);
  }

  suggestions() {
    return this._send('suggestions', {}, 10000);
  }

  campaigns() {
    return this._send('campaigns', {}, 10000);
  }

  status() {
    return {
      available: this.available,
      lastError: this.lastError,
    };
  }

  stop() {
    if (this.proc) {
      try { this.proc.kill(); } catch (_) { /* ignore */ }
    }
  }
}

module.exports = new ChatbotClient();
module.exports.ChatbotClient = ChatbotClient;
